[server]
# server_id = 1
channel_id = [1, 2]
privilege_group_id = 5
# redis_server = ""
ignore_user = ["serveradmin"]
whitelist_ip = []
# redis_server = ""
# track_channel_member = ""

# [mute_porter]
# enable = false
# monitor = 1
# target = 1
# Should use database ID
# whitelist = []

# [[permissions]]
# channel_id = 1
# it means set i_channel_needed_permission_modify_power to 75 and i_channel_needed_delete_power to 60
# See: https://github.com/KunoiSayami/teamspeak-autochannel.rs/wiki/Permission-List for more key information
# map = [[86, 75], [133, 60]]

[misc]
# interval = 5

# [custom_message]
# move_to_channel = "You have been moved into your channel."

[telegram]
api_key = ""
target = 0
api_server = ""

# [raw_query]
# server = ""
# port = 10011
# user = "serveradmin"
# password = "114514"