additional = [] # Additional configure filename
[server]
server-id = 1 # Server ID
channel-id = [1, 2] # Channel ID
privilege-group-id = 5 # Channel Privilege Group ID
ignore_user = ["serveradmin"]
whitelist_ip = []
# redis-server = "" # Redis Server Address
leveldb = "" # LevelDB database file name/path
# track-channel-member = ""

# [mute-porter]
# enable = false
# monitor = 1
# target = 1
# Should use database ID
# whitelist = []

# [[permissions]]
# channel-id = 1
# it means set i_channel_needed_permission_modify_power to 75 and i_channel_needed_delete_power to 60
# See: https://github.com/KunoiSayami/teamspeak-autochannel.rs/wiki/Permission-List for more key information
# map = [[86, 75], [133, 60]]

[misc]
interval = 5 # Interval (milliseconds)

# [custom-message]
# move-to-channel = "You have been moved into your channel."

[telegram]
api-key = ""
target = 0
# api-server = ""
# responsible = false
# allowed-chat = []

[raw-query]
server = ""  # TeamSpeak Server Address
port = 10011 # TeamSpeak ServerQuery(Raw) Port
user = "serveradmin" # TeamSpeak ServerQuery Username
password = "114514" # TeamSpeak ServerQuery Password