#!/bin/bash
[ ! -r /var/lib/dbus/machine-id ] && dbus-uuidgen | sudo tee /var/lib/dbus/machine-id
grep "Dinternal_pcre" PKGBUILD || exit
sed -i 's/gtk_doc=false \\/gtk_doc=false/g' PKGBUILD
sed -i 's/-Dinternal_pcre=false//g' PKGBUILD
