FROM repobuildbase:latest

RUN echo -e "\n[archlinuxcn]\nServer = https://repo.archlinuxcn.org/$$arch\n" >> /etc/pacman.conf

RUN pacman-key --init

RUN pacman --noconfirm --needed -Sy archlinuxcn-keyring

RUN pacman --noconfirm --needed -Su base-devel gnupg git yay

RUN useradd -m build

RUN echo 'build ALL=(ALL) NOPASSWD:ALL' > /etc/sudoers

COPY dockerbuild.sh /home/build/

USER build

ENTRYPOINT ["bash", "-c", "/home/build/dockerbuild.sh"]
