FROM repobuildbase:latest

ARG REMOTE_ADDRESS

RUN echo -n -e '\n[kunoisayami]\nServer = ' >> /etc/pacman.conf

RUN echo ${REMOTE_ADDRESS} >> /etc/pacman.conf

RUN pacman-key --init

RUN curl -fL https://keys.openpgp.org/vks/v1/by-fingerprint/4A0F0C8BC709ACA4341767FB243975C8DB9656B9 | pacman-key --add -

RUN pacman-key --finger 4A0F0C8BC709ACA4341767FB243975C8DB9656B9

RUN pacman-key --lsign-key 4A0F0C8BC709ACA4341767FB243975C8DB9656B9

RUN useradd -m build

COPY initfolder.sh hook*.sh /home/build/

RUN if [ -r /home/build/hook.sh ]; then /home/build/hook.sh; fi

RUN if [ ! -r /home/build/hook.sh ]; then pacman --noconfirm --needed -Sy reflector; fi

RUN if [ ! -r /home/build/hook.sh ]; then reflector --save /etc/pacman.d/mirrorlist --latest 2 --sort rate; fi

RUN pacman --noconfirm --needed -Sy archlinux-keyring

RUN pacman --noconfirm --needed -Su base-devel gnupg git yay

RUN pacman --noconfirm --needed -S  python python-aiohttp python-aiofiles python-aiohttp-socks python-asycio-timeout moreutils

RUN echo 'build ALL=(ALL) NOPASSWD:ALL' > /etc/sudoers

ADD repos /home/build/repos

COPY dockerbuild.sh entrypoint.sh /home/build/

RUN /home/build/initfolder.sh

RUN if [ -r /home/build/hook-99.sh ]; then /home/build/hook-99.sh; fi

USER build

# ENTRYPOINT ["bash", "-c", "/home/build/repos/utils/pkgbuild_bootstrap"]

ENTRYPOINT ["bash", "-c", "/home/build/entrypoint.sh"]
