#!/bin/bash

if [ -z "$DOCKER_SETUP_SCRIPT" ]; then
  echo $GPG_PRIV_KEY | base64 -d | gpg --import
  cd "$(dirname "$0")"
  cd ../../
  echo "Current pwd: $(pwd)"
  sudo pacman -Sy
fi

set -Eeo pipefail
trap cleanup SIGINT SIGTERM ERR EXIT

cleanup() {
	trap - SIGINT SIGTERM ERR EXIT
	unset SRCDEST
	unset CONFDEST
	unset TMPCONF
	unset FLAGS
	unset ARCH
}

ARCH=$(uname -m)
CONFDEST="${PWD}/makepkg.d/makepkg.$ARCH.conf"

TMPCONF="makepkg_current.conf"
cat "${PWD}/makepkg.d/makepkg.base.conf" > "$TMPCONF"
cat "$CONFDEST" >> "$TMPCONF"

FLAGS=""

if [ "$EUID" -eq 0 ] ; then
  echo "\033[0;32mPlease run this script as non-root\033[0m"
  exit 3
fi

if [ -z "$REMOTE_DATABASE" ]; then
  echo "\033[0;32mYou should specify remote address\033[0m"
  exit 4
fi

if [ -n "$FORCE_BUILD_ALL" ]; then
  FLAGS+="--build-all "
fi

if [ -n "$BUILD_FAIL_FAST" ]; then
  FLAGS+="--fail-fast "
fi

curl -fL -o remote.db "$REMOTE_DATABASE"


./utils/pkgbuild.py remote.db $FLAGS
